GEMINI_API_KEY = "AIzaSyDjXLOOgmWZC6WXAy1yQp1P3cIbSD_HR60"
WP_URL = "https://morroc.net/wp-json/wp/v2/posts"
WP_USER = "yronmorroc"
WP_APP_PASSWORD = "RqUy LeS9 4BVv eRZw QvHT otH8"
APP_PASSWORD = "yronggezggbitch"